[package]
name = "lsystem"
version = "0.1.0"
authors = ["Piripant <piripant@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.22.1"
nalgebra = "0.18.0"
serde = { version = "1.0.98", features = ["derive"] }
serde_yaml = "0.8.9"
clap = "2.33.0"