axiom: F+F+F+F

start_state:
  'color_r': 255
  'step': 7

rules:
  'F': FF+F-F+F+FF

commands:
  'F':
    - forward
    - add color_r -1
    - add color_g 2
    - add color_b 4
  '+':
    - clockwise
  '-': 
    - counterclockwise