axiom: F+XF+F+XF

start_state:
  'color_r': 255
  'step': 10
  'turning_angle': 60

rules:
  X: XF-F+F-XF+F+XF-F+F-X

commands:
  'F':
    - forward
  '+':
    - counterclockwise
  '-': 
    - clockwise